### PR TITLE
Don't skip the first namespace for controller paths

### LINKED ISSUE #79: Autoloading controllers in extension `lib` stopped working
(originally reported here, but moving it [here](https://github.com/solidusio/solidus_auth_devise/issues/210#issuecomment-1587364990), as it affects not only `solidus_auth_devise`, but also `solidus_braintree`.

I'm experiencing the following error in a brand new Solidus Sandbox: Currently (Solidus `main` as of https://github.com/solidusio/solidus/commit/78d20c41b61c8fd3e708c3871030f4e6a5948628, `solidus_auth_devise` version 2.5.8) the sandbox can't find the backend sessions controller. This is the error when you try:

```
Started GET "/admin/" for 127.0.0.1 at 2023-06-12 15:37:29 +0200
  ActiveRecord::SchemaMigration Pluck (0.1ms)  SELECT "schema_migrations"."version" FROM "schema_migrations" ORDER BY "schema_migrations"."version" ASC
Processing by Spree::Admin::RootController#index as HTML
Redirected to http://localhost:3000/admin/login
Completed 302 Found in 340ms (ActiveRecord: 0.8ms | Allocations: 530212)


Started GET "/admin/login" for 127.0.0.1 at 2023-06-12 15:37:29 +0200
  
ActionController::RoutingError (uninitialized constant Spree::Admin::UserSessionsController

      Object.const_get(camel_cased_word)
            ^^^^^^^^^^
Did you mean?  UserPasswordsController

            raise MissingController.new(error.message, error.name)
            ^^^^^):
  
```

```sh 
bin/rails zeitwerk:check
```
 results in
 
``` 
Hold on, I am eager loading the application.

WARNING: The following directories will only be checked if you configure
them to be eager loaded:

  /home/anselm/.gem/ruby/3.1.4/gems/solidus_paypal_commerce_platform-1.0.1/app/decorators/models
  /home/anselm/.gem/ruby/3.1.4/gems/solidus_auth_devise-2.5.8/lib/decorators/backend/controllers
  /home/anselm/.gem/ruby/3.1.4/gems/solidus_auth_devise-2.5.8/lib/controllers/backend/spree

You may verify them manually, or add them to config.eager_load_paths
in config/application.rb and run zeitwerk:check again.

Otherwise, all is good!
``` 

**Solidus Version**:

Solidus `main` as of https://github.com/solidusio/solidus/commit/78d20c41b61c8fd3e708c3871030f4e6a5948628

**To Reproduce**

The simplest check for this is just running the rails console and typing the name of the controller we need. If all is good, the REPL should return the constant, if something's off, we get an undefined constant error:

```rb
=> Spree::Admin::UsersController
irb(main):007:0> Spree::Admin::UserSessionsController
(irb):7:in `<main>': uninitialized constant Spree::Admin::UserSessionsController (NameError)
Did you mean?  Spree::Admin::UsersController
```

This behavior occurs not just with `solidus_auth_devise`, but with any gem that has the backend controllers in `lib`. One example is `solidus_braintree`, with its `SolidusBraintree::ConfigurationsController`: 

``` rb
irb(main):002:0> SolidusBraintree
=> SolidusBraintree
irb(main):003:0> SolidusBraintree::ConfigurationsController
(irb):3:in `<main>': uninitialized constant SolidusBraintree::ConfigurationsController (NameError)
``` 

**Current behavior**

```rb
irb(main):002:0> SolidusBraintree::ConfigurationsController
(irb):3:in `<main>': uninitialized constant SolidusBraintree::ConfigurationsController (NameError)
```
**Expected behavior**

```rb
irb(main):002:0> SolidusBraintree::ConfigurationsController
=> SolidusBraintree::ConfigurationsController
```

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Fedora Linux
 - Browser [e.g. chrome, safari] Firfox, but it doesn't really matter.
 - 
**Additional context**

This stopped working with the following commit: https://github.com/solidusio/solidus_support/commit/17e871839e754bd5a247b99b21ca913f50700db9

### PR DESCRIPTION
**Pull request by elia**
- Fixup to https://github.com/solidusio/solidus_support/pull/78
- Fixes https://github.com/solidusio/solidus_support/issues/79

## Summary

Autoload paths are meant to list autoload roots and not the first level of the namespace.

E.g. having the following controller in lib/controllers/solidus_foo:

    lib/controllers/solidus_foo/spree/my_controller.rb

The autoload will be triggered by a constant reference to `Spree::MyController` targeting `spree/my_controller.rb` inside `lib/controllers/solidus_foo/`. This means the autoload path needs to be `lib/controllers/solidus_foo/`.

See also https://edgeguides.rubyonrails.org/classic_to_zeitwerk_howto.html#globs-in-config-autoload-paths

## Checklist

Check out our [PR guidelines](https://github.com/solidusio/.github/blob/master/CONTRIBUTING.md#pull-request-guidelines) for more details.

The following are mandatory for all PRs:

- [ ] I have written a thorough PR description.
- [ ] I have kept my commits small and atomic.
- [ ] [I have used clear, explanatory commit messages](https://github.com/solidusio/.github/blob/main/CONTRIBUTING.md#writing-good-commit-messages).

The following are not always needed:

- 📖 I have updated the README to account for my changes.
- 📑 I have documented new code [with YARD](https://www.rubydoc.info/gems/yard/file/docs/Tags.md).
- 🛣️ I have opened a PR to update the [guides](https://github.com/solidusio/edgeguides).
- ✅ I have added automated tests to cover my changes.
- 📸 I have attached screenshots to demo visual changes.

### CODE REVIEW

**Comment by elia** [comment]
@DanielePalombo @mamhoff can you confirm if fixes the issue for your projects?

File: lib/solidus_support/engine_extensions.rb [hunk 1]
```diff
@@ -110,7 +110,7 @@ def enable_solidus_engine_support(engine)
           decorators_path = root.join("lib/decorators/#{engine}")
           controllers_path = root.join("lib/controllers/#{engine}")
           config.autoload_paths += decorators_path.glob('*')
-          config.autoload_paths += controllers_path.glob('*')
+          config.autoload_paths << controllers_path if controller_path.exist?
```
Comment (mamhoff) [inline lib/solidus_support/engine_extensions.rb]: This works, but should the line 112 (just above) not receive the same treatment?

Comment (elia) [reply lib/solidus_support/engine_extensions.rb]: Good call, I'd expect that folder to have an additional layer and be similar to `app/` in that regard, eg. ~~`lib/decorators/solidus_foo/models/spree/product/my_decorator.rb`~~ `lib/decorators/frontend/models/spree/product/my_decorator.rb`

An example from auth devise:

```
lib/decorators/frontend/controllers/spree/checkout_controller_decorator.rb
```

**Review by DanielePalombo — APPROVED** [review]
LGTM.

**Review by kennyadsl — APPROVED** [review]

**Comment by kennyadsl** [comment]
Released in 0.9.3
